services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppVerk\SectionBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Doctrine,Twig}'

    AppVerk\SectionBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    AppVerk\SectionBundle\Twig\TemplateExtension:
